sudo: false
language: python
python:
  - '2.7'
install:
  - pip install --upgrade pip
  - pip --version
  - pip install -r requirements.txt
  - pip install -U twine
script:
  - ln -s ansible-shell ansible-shell.py && python -m compileall ansible-shell.py
  - rm -f ansible-shell.py ansible-shell.pyc
  - echo 'date' | ./ansible-shell -i tests/localhost
  - echo '\hostname' | ./ansible-shell -i tests/localhost | fgrep $(hostname)
deploy:
  provider: pypi
  upload_docs: no
  user: dominis
  password:
    secure: cYK+F4UlCtJ/xLfQprGyytAqsHSZni2ZfRwvnLxgvS5DIapdDiDNuFhnfpoS53K86yav5MIN5AQVUgfwejVwlzFDNv9rPMTAy+/sY8BpcCkekkZGHWB+HxaPXhi2YZAj5E+b+7frZ4PODE/RjzoyayYLrpcxvS8M1gDxtQ8U7Ns=
  on:
    tags: true
    repo: dominis/ansible-shell
    branch: master
